<?php
/**

 *
 * @category    Dotsquares
 * @package     Dotsquares_Marketplace
 * @version     3.5.2
 * @author      Dotsquares Team <developers@dotsquares.com>
 * @copyright   Copyright (c) 2016 Dotsquares. (http://www.dotsquares.com)
 * @license     http://www.dotsquares.com/LICENSE.txt
 *
 */
?>
<?php
/**
 * Shopping cart template
 *
 * @var $block \Magento\Checkout\Block\Cart
 */
$customerSession = $block->getSessionValue();
if($customerSession->getMyValue()){
?>
<span class="alert"><?php echo $customerSession->getMyValue();?></span>
<?php
}
if ($block->getItemsCount()) {
    echo $block->getChildHtml('with-items');
} else {
    echo $block->getChildHtml('no-items');
}

$customerSession->unsMyValue();