<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create("Magento\Customer\Model\Session");
  
$resource = $objectManager->create('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection('core_write');
$table =  $connection->getTableName('sales_order_grid');
// echo $QURY = 'SELECT * FROM ' . $table .' WHERE product_ids LIKE "%'.$product->getId().'%"';
$QURY = 'SELECT * FROM ' . $table .' WHERE customer_id = '. $customerSession->getCustomer()->getId();  
// $QURY = 'SELECT * FROM ' . $table .' WHERE status=1 AND FIND_IN_SET('.$product->getId().',product_ids) > 0 AND '. $andopration;

$dotsquaress = $connection->fetchAll($QURY);

$enabl = 1;
$oroption ='';
if(count($dotsquaress) < 1) {
  $enabl = 0;
	$oroption = '<option value="" >No Orders found</option>';
}else{
	$oroption = '<option value="" >---Select Orders Number---</option>';
  foreach($dotsquaress as $orde){
    // $fileaccessURL = $mediaUrl.'uploadfiles'.$files['file_name'];
    $ordeID = $orde['increment_id'];
    // $medianame = $files['name'];  
    if($oroption ==''){
     $oroption = '<option value="'.$ordeID.'" >'.$ordeID.'</option>';
    }else{
      $oroption = $oroption.'<option value="'.$ordeID.'" >'.$ordeID.'</option>';
    }
  }
}


$conf_text_submit_button_text = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('gernal_section_ds/general/text_submit_button_text');
 // $conf_dropdown_enable = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('gernal_section_ds/general/dropdown_enable');
  
$conf_dropdown_reason_for_nquiry = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('gernal_section_ds/enquiry_Change_label_of_fields/dropdown_reason_for_nquiry');

if($conf_dropdown_reason_for_nquiry) {
  $conf_dropdown_reason_for_nquiry_export = explode(',', $conf_dropdown_reason_for_nquiry);
} else {
  $conf_dropdown_reason_for_nquiry_export = array();
}

  
?>
<form class="form ecommerce" action="<?php echo $this->getUrl('enquiry/customer/filldata'); ?>" name="enquiryform" id="ecommerceform" method="post" enctype="multipart/form-data" data-mage-init='{"validation": {}}'>


<fieldset class="fieldset">

<div class="field field-name-firstname required">
            <label class="label" for="firstname">
                <span></span>
            </label>

            <div class="control">
                 Required Fields.
            </div>
        </div>

        <div class="field field-name-name required">
            <label class="label" for="name">
                <span>Reason for Enquiry</span>
            </label>

            <div class="control">
			<select name="name" class="input-text required-entry">
			
			  <option value="">---Please select your Reason---</option>
			  <?php 
			  foreach($conf_dropdown_reason_for_nquiry_export as $mak){
				  echo '<option value="'.trim($mak).'">'.trim($mak).'</option>';
			  }
			  ?>
			  
			</select>
                <!--<input value="<?php //echo escapeHtml($this->helper('Jute\Ecommerce\Helper\Data')->getUserName()) ?>" class="input-text" type="text" />-->
            </div>
        </div>
		
		 <div class="field field-name-odernsmb required">
            <label class="label" for="dotsquares_number">
                <span>Orders Number</span>
            </label>

            <div class="control">
                <select name="dotsquares_number" class="input-text required-entry">
			         <?php 
					  echo $oroption;
					 ?>
			     </select>
            </div>
      </div>
		
		  <div class="field field-name-enquiry required">
            <label class="label" for="enquiry_content">
                <span>Enquiry</span>
            </label>

            <div class="control">
               <textarea name="enquiry_content" cols="35" rows="4" class="input-text required-entry"></textarea>
            </div>
        </div>
		

<!--<legend class="legend"><span><?php //echo __('Dotsquares Enquiry') ?></span></legend><br />-->
 

 <input type="hidden" value="<?php echo $customerSession->getCustomer()->getId(); ?>" name="client_id" />
 
</fieldset>

<div class="actions-toolbar">
        <div class="primary">
            <?php $conf_text_submit_button_text = $conf_text_submit_button_text ? $conf_text_submit_button_text : "Submit"; ?>
            <button type="submit" class="action save primary" title="<?php echo $conf_text_submit_button_text; ?>"><span><?php echo $conf_text_submit_button_text; ?></span></button>
        </div>
        
    </div>

</form>
<?php
/* }else{
	echo '<strong>Please confiure orders enquiry extension.</strong>';  
	//echo '<strong>Web Page Under Construction.</strong><br/><span>Come Back Soon...</span>'; 
  } */

  ?>