<?php
/**

 *
 * @category    Dotsquares
 * @package     Dotsquares_Marketplace
 * @version     3.5.2

 *
 */

$attributes=$this->getData('attributes');
$productDetail=$this->getData('productdetail');
foreach ( $attributes as $attribute ) {
                    /**
                      * Get the value for a specific attribute for a simple product
                      */
                $attributeId = $attribute->getProductAttribute ()->getAttributeId ();
                $optionValue = $productDetail->getData ( $attribute->getProductAttribute ()->getAttributeCode () );
                ?>
    <input type="hidden"
       name="super_attribute[<?php echo $attributeId; ?>]"
       value="<?php echo $optionValue; ?>">
    <?php } ?>