<?php
/**
 * Dotsquares
 * NOTICE OF LICENSE
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.dotsquares.com/LICENSE.txt
 * ==============================================================
 * MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Dotsquares does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Dotsquares does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category Dotsquares
 * @package Dotsquares_Marketplace
 * @version 3.5.2
 * @author Dotsquares Team <developers@dotsquares.com>
 * @copyright Copyright (c) 2022 Dotsquares. (http://www.dotsquares.com)
 * @license http://www.dotsquares.com/LICENSE.txt
 */
?>
<?php
$optionCount=$this->getData('optioncount');
$optionIsRequire=$this->getData('optionrequire');
?>

<select   name="product[options][<?php echo $optionCount; ?>][is_require]"
id="product_option_<?php echo $optionCount;  ?>_is_require"
class="select" title="">
<option value="1"
        <?php
        if (isset ( $optionIsRequire ) && $optionIsRequire == 1) {
            echo 'selected';
        }
        ?>><?php echo __('Yes'); ?></option>
                                    <option value="0"
                                        <?php
    if (isset ( $optionIsRequire ) && $optionIsRequire == 0) {
     echo 'selected';
    }
    ?>><?php echo __('No'); ?></option>
                            </select>