<?php
/**
 * Dotsquares
 * NOTICE OF LICENSE
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.dotsquares.com/LICENSE.txt
 * ==============================================================
 * MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Dotsquares does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Dotsquares does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category Dotsquares
 * @package Dotsquares_Marketplace
 * @version 3.5.2
 * @author Dotsquares Team <developers@dotsquares.com>
 * @copyright Copyright (c) 2022 Dotsquares. (http://www.dotsquares.com)
 * @license http://www.dotsquares.com/LICENSE.txt
 */
?>
<div class="actions-toolbar">
    <div class="primary">
        <button id="btn_save_product" type="button"
            class="action submit primary"
            title="<?php echo __('Save') ?>">
            <span><?php echo __('Save') ?></span>
        </button>
    </div>
</div>