<?php
echo $this->getMessagesBlock()->getGroupedHtml();
?>
<?php
$_datasets = $this->getDatasets();
$id        = explode(',', $this->getId());
?>
<?php //echo $this->getPagerHtml(); 
?>
<?php
if ($_datasets->getSize()):
?>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script> 
<script type="text/javascript" src="<?php
    echo $this->getSkinUrl('js/dsofferbanner/jquery.downCount.js');
?>"></script> 
<table cellspacing="0" class="data-table" id="data-table">
    <tbody>
        <?php
    foreach ($_datasets as $_dataset):
?>
        <?php
        $status   = $_dataset->getData('status');
        $bannerid = $_dataset->getData('offer_banner_id');
		$test=$this->getId();
        if (!empty($test)) {
            if (in_array($bannerid, $id)) {
                if ($status == 0) {
?>
         <?php
                    $start_date = $_dataset->getData('start_date');
                    //$start = date('Y-m-d', strtotime($start_date));
                    $end_date   = $_dataset->getData('end_date');
                    //$end = date('Y-m-d', strtotime($end_date));
                    
                    $start = strtotime($start_date);
                    $end   = strtotime($end_date);
                    
                    list($year, $month, $day, $hours, $minutes, $second) = split('[/.-]', $end_date);
                    $current_date = date("Y-m-d h:i:00");
                    $current      = strtotime($current_date);
                    if ($end <= $current) {
                    } else {
                        if ($start <= $current) {
                            
                            if ($start <= $end) {
                                $finaldate = $year . '/' . $month . '/' . $day;
?>
           <tr>
           <td  valign="middle" style="vertical-align:middle;">
            <div class="img-offer-thumb">
            <a href="<?php
                                echo $_dataset->getData('url');
?>" target="_blank">
           <img style="background:url(<?php
                                echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $_dataset->getData('image');
?>) no-repeat scroll center center / 100%" />
             <div class="offer-banner"><span class="offer-banner-title"><?php
                                echo $_dataset->getData('title');
?></span>
            <ul class="countdown" id="banner<?php
                                echo $_dataset->getData('offer_banner_id');
?>">
<li> <span class="days">00</span>
<p class="days_ref">days</p>
</li>
<li class="seperator">:</li>
<li> <span class="hours">00</span>
<p class="hours_ref">hours</p>
</li>
<li class="seperator">:</li>
<li> <span class="minutes">00</span>
<p class="minutes_ref">minutes</p>
</li>
<li class="seperator">:</li>
<li> <span class="seconds">00</span>
<p class="seconds_ref">seconds</p>
</li>
</ul>
            <p class="offer-banner-content"><?php
                                echo $_dataset->getData('content');
?></p>
            </a>
            </div> </div></td>
  		<!--<td  valign="middle" style="vertical-align:middle;"><a href="#" ><?php //echo($this->__('View')) 
?></a></td>-->
            </tr>
      <?php
                            }
                        }
                    }
                }
            }
        } else {
            if ($status == 0) {
?>
        
         <?php
                $start_date = $_dataset->getData('start_date');
                //$start = date('Y-m-d', strtotime($start_date));
                $end_date   = $_dataset->getData('end_date');
                //$end = date('Y-m-d', strtotime($end_date));
                
                $start = strtotime($start_date);
                $end   = strtotime($end_date);
                
                list($year, $month, $day, $hours, $minutes, $second) = split('[/.-]', $end_date);
                $current_date = date("Y-m-d h:i:00");
                $current      = strtotime($current_date);
                if ($end <= $current) {
                } else {
                    if ($start <= $current) {
                        
                        if ($start <= $end) {
                            $finaldate = $year . '/' . $month . '/' . $day;
                            
?>
 
           <tr>
           <td  valign="middle" style="vertical-align:middle;">
            <div class="img-offer-thumb">
            <a href="<?php
                            echo $_dataset->getData('url');
?>" target="_blank">
           <img style="background:url(<?php
                            echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $_dataset->getData('image');
?>) no-repeat scroll center center / 100%" />
             <div class="offer-banner"><span class="offer-banner-title"><?php
                            echo $_dataset->getData('title');
?></span>
            <ul class="countdown" id="banner<?php
                            echo $_dataset->getData('offer_banner_id');
?>">
			<li> <span class="days">00</span><p class="days_ref">days</p></li>
			<li class="seperator">:</li><li> <span class="hours">00</span><p class="hours_ref">hours</p></li>
            <li class="seperator">:</li><li> <span class="minutes">00</span><p class="minutes_ref">minutes</p></li><li class="seperator">:</li>
			<li> <span class="seconds">00</span><p class="seconds_ref">seconds</p></li>
            </ul>
            <p class="offer-banner-content"><?php
                            echo $_dataset->getData('content');
?></p>
            </a>
            </div> </div></td>
  		<!--<td  valign="middle" style="vertical-align:middle;"><a href="#" ><?php //echo($this->__('View')) 
?></a></td>-->
            </tr>
      <?php
                        }
                    }
                }
            }
        }
?>
	   <script class="source123" type="text/javascript">
        $('#banner<?php
        echo $_dataset->getData('offer_banner_id');
?>').downCount({
            date: '<?php
        echo $finaldate;
?>',
            offset: +0
        }, function () {
            //alert('WOOT WOOT, done!');
        });
        </script> 
	   <?php
    endforeach;
?>
    </tbody>
</table>

<?php //echo $this->getPagerHtml(); 
?>
<?php
else:
?>
    <p><?php
    echo $this->__('You have submited no data.');
?></p>
<?php
endif;
?>
<link href="<?php
echo $this->getSkinUrl('css/dsofferbanner/offerbanner.css');
?>" rel="stylesheet" type="text/css">


<script type="text/javascript">
jQuery.noConflict();
</script> 

