<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<small class="copyright">
    <span>© 2002 - <?= date("Y") ?> Dotsquares Ltd. All rights reserved.</span>
</small>
<script>
    require([
        'jquery',
        'accordion'], function ($) {
        $(".faq_according").accordion();

        $(window).scroll(function(){ 
            if ($(this).scrollTop() > 100) { 
                $('.page-header').addClass("header-sticky"); 
            } else { 
                $('.page-header').removeClass("header-sticky");  
            } 
        });
    });
</script>

