<div id="salesforce-messages" style="display: none;">
    <div class="messages">
        <div class="message">
            <div data-ui-id="salesforce-messages"></div>
        </div>
    </div>
</div>
<div class="actions actions-get-auth-token btn-authorization">
    <button class="action-validate-get-auth-token" type="button" data-ui-id="button-send-request-to-salesforcecrm" id="<?php echo $block->getHtmlId() ?>">
        <span><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
<script>
    require(['jquery'], function (jQuery) {
        jQuery('#salesforcecrm_config').on('keyup', '[data-ui-id="text-groups-config-fields-email-value"], [data-ui-id="text-groups-config-fields-client-id-value"], [data-ui-id="text-groups-config-fields-client-secret-value"], [data-ui-id="text-groups-config-fields-security-token-value"]', function () {
            jQuery(this).val(jQuery(this).val().trim());
        });
        jQuery('[data-ui-id="button-send-request-to-salesforcecrm"]').click(function () {
            if (jQuery(this).parents('form').valid()) {
                var username = jQuery('[data-ui-id="text-groups-config-fields-email-value"]').val().trim();
                var password = jQuery('[data-ui-id="system-config-form-field-password-0-password-groups-config-fields-passwd-value"]').val().trim();
                var client_id = jQuery('[data-ui-id="text-groups-config-fields-client-id-value"]').val().trim();
                var client_secret = jQuery('[data-ui-id="text-groups-config-fields-client-secret-value"]').val().trim();
                var security_token = jQuery('[data-ui-id="text-groups-config-fields-security-token-value"]').val().trim();
                var connect_environment = jQuery('[data-ui-id="select-groups-config-fields-connect-environment-value"]').val().trim();
                var data = {
                    username           : username,
                    password           : password,
                    client_id          : client_id,
                    client_secret      : client_secret,
                    security_token     : security_token,
                    connect_environment: connect_environment,
                    form_key           : FORM_KEY
                };
                var url = '<?php echo $block->getUrl('salesforce/system_config_getauth/getAuth'); ?>';
                jQuery.ajax({
                    type      : "POST",
                    url       : url,
                    data      : data,
                    showLoader: true,
                    success   : function (response) {
                        var result_token = jQuery('[data-ui-id="salesforce-messages"]');
                        var responseObj = JSON.parse(response);
                        if (responseObj.error === 1) {
                            result_token.html(responseObj.message.toUpperCase());
                            result_token.parent('div.message').addClass('message-error').parents('div#salesforce-messages').show();
                        } else {
                            jQuery('[data-ui-id="system-config-form-field-disable-0-text-groups-config-fields-access-token-value"]').val(responseObj.access_token);
                            jQuery('[data-ui-id="system-config-form-field-disable-0-text-groups-config-fields-instance-url-value"]').val(responseObj.instance_url);
                            jQuery('[data-ui-id="button-send-request-to-salesforcecrm"]').attr('disabled', 'disabled');
                            result_token.html('<?=__('Get Access Token Success')?>');
                            result_token.parent('div.message').removeClass('message-error').addClass('message-success').parents('div#salesforce-messages').show();
                            location.reload();
                        }
                    },
                    error     : function () {
                        var result_token = jQuery('[data-ui-id="salesforce-messages"]');
                        result_token.html('<?=__('Please check the configuration again')?>');
                        result_token.parent('div.message').addClass('message-error').parents('div#salesforce-messages').show();
                    }
                });
            }
        });
    });
</script>