<?php $featuredproduct = $block->getFeaturedProducts();  
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$productHelper = $this->helper('Magento\Catalog\Helper\Product');
	$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
	$list  = count($featuredproduct);
	$limit = $objectManager->create('Ds\Featuredproducts\Helper\Data')->getConfig('featuredproducts/general/limit');
	$i = 0;
	$columcount = 5;
?>
	<div class="container">
		<h3 class="sc_title sc_title_center sc_lines inner-hed">
			<span>Featured Product </span>
		</h3>
		<div class="jcarousel-wrapper">
			<div class="feaproduct_list jcarousel">
				<ul class="bxslider">
					<?php foreach ($featuredproduct as $product){
						$productObject = $objectManager->create('Magento\Catalog\Model\Product'); 
						$_product = $productObject->load($product->getId());
						$imgUrl = '';
						$imgUrl= $productHelper->getSmallImageUrl($_product); 
						
					?>	
							<li class="item productli <?php echo 'product'.$i; ?>">
								<a href = "<?php echo $_product->getProductUrl() ?>">
									<img src="<?php echo $imgUrl ?>" />
									<p class="products-name"><?php echo $_product->getName() ?></p>
								</a>
								<div class="price_label">
									<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
									<?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency(number_format($_product->getPrice(),2),true,false); ?>
								</div>
								<div class="product-item-inner">
									<?php /*<div data-role="add-to-links" class="actions-secondary">
										<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
											<a href="#" 
											   class="action towishlist"
											   title="<?php echo $block->escapeHtml(__('Add to Wishlist')); ?>"
											   aria-label="<?php echo $block->escapeHtml(__('Add to Wishlist')); ?>"
											   data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'
											   data-action="add-to-wishlist"
											   role="button">
												<span><i class="fa fa-heart-o"></i><?php //echo __('Add to Wishlist') ?></span>
											</a>
										<?php endif; ?>
										<?php
										$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
										?>
										<a href="#"
										   class="action tocompare"
										   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
										   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
										   data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>'
										   role="button">
											<span><i class="fa fa-exchange"></i><?php //echo __('Add to Compare') ?></span>
										</a>
									</div> */ ?>
		<div class="actions-primary">
			<?php if ($_product->isSaleable()): ?>
				<?php $postParams = $block->getAddToCartPostParams($_product); ?>
				<?php echo $block->getBlockHtml('formkey')?>
			<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();

  $listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');

  $addToCartUrl =  $listBlock->getAddToCartUrl($product); ?>

  <form data-role="tocart-form" action="<?php echo $addToCartUrl; ?>" method="post"> 

    <?php echo $block->getBlockHtml('formkey')?>

     <button type="submit" title="Add to Cart" class="action tocart primary">

       <span>Add to Cart</span>
     </button>
 </form>
			<?php else: ?>
				<?php if ($_product->getIsSalable()): ?>
					<div class="stock available"><span><?php echo __('In stock') ?></span></div>
				<?php else: ?>
					<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
				<?php endif; ?>
			<?php endif; ?>
		</div>
	
								</div>
							</li>
							
						
						<?php 
					}	?>	
				</ul>
			</div>	

		</div>	
	</div>
	
<script type="text/javascript">
	jQuery('.bxslider').bxSlider({
  minSlides: 3,
  maxSlides: 4,
  slideWidth: 275,
   moveSlides: 1,
  slideMargin: 10
});


</script>
