<?php
	use Magento\Store\Model\ScopeInterface;
	
	//$enabled = $block->_scopeConfig->getValue('despatchtimer/settings/enabled', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
	$enabled = $block->getConfigValue('despatchtimer/settings/enabled');
	if($enabled) :
	//$next_despatch_time = $this->displayTimer();
	/* @var $block \DS\Despatchtimer\Block\Product\View\Extra */
	$next_despatch_time = $block->displayTimer();
	// 86400 seconds = 1 day
?>
	<div class="despatch-timer" style="margin-bottom: 5px; clear: both;">
		<?php echo 'NEXT DISPATCH IN: '?>
		<script type="application/javascript">
			var myCountdown1 = new Countdown({
								time: <?php echo $next_despatch_time ?>, 
								width:160, 
								height:30,  
								rangeHi: "day",
								style:"flip"	// <- no comma on last item!
								});

		</script>
	</div>
<?php endif; ?>