<?php
/**
 * Dotsquares
 * NOTICE OF LICENSE
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.dotsquares.com/LICENSE.txt
 * ==============================================================
 * MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Dotsquares does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Dotsquares does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category Dotsquares
 * @package Dotsquares_Marketplace
 * @version 3.5.2
 * @author Dotsquares Team <developers@dotsquares.com>
 * @copyright Copyright (c) 2022 Dotsquares. (http://www.dotsquares.com)
 * @license http://www.dotsquares.com/LICENSE.txt
 */
?>
<?php $sellerInformation=$block->getAllsellerdatas()->getData(); ?>
<?php $sellerCount=count($sellerInformation);?>
<?php if($sellerCount>=1){?>
<div class="my-account-wrapper">
    <ul class="mp_all_sellers_container f-left" border="0"
        cellspacing="0" cellpadding="0">
      <?php
 foreach ( $sellerInformation as $sellerData ) {
  $sellerDatas = $block->getSellerrequestpath ( $sellerData );
  ?>
       <li class="f-left"><a class="mp_all_sellers_view"
            href="<?php echo $block->getUrl($sellerDatas['request_path']);?>"
            title="<?php echo $sellerDatas['store_name'];?>">
           <?php if($sellerDatas['logo_name']!=""){?>
           <img
                src="<?php echo $sellerDatas['logo_path'].$sellerDatas['logo_name'];?>"
                alt="Store Logo" class="store-logo">
           <?php } else{?>
           <img
                src="<?php echo $block->getViewFileUrl('Dotsquares_Marketplace::images/no-store-logo.png');?>"
                alt="Store Logo" class="store-logo">
         <?php  }?>
         <span style="clear: both; text-transform: uppercase;"><?php echo $sellerDatas['store_name'];?></span>
        </a></li>
      <?php }?>
 </ul>
</div>
      <?php if ($block->getPagerHtml()): ?>
        <div class="allseller-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php

} else {
    echo __ ( 'No Registered Seller Records Were Found' );
}

?>