<?php
/**
 * Dotsquares
 * NOTICE OF LICENSE
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.dotsquares.com/LICENSE.txt
 * ==============================================================
 * MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Dotsquares does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Dotsquares does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category Dotsquares
 * @package Dotsquares_Marketplace
 * @version 3.5.2
 * @author Dotsquares Team <developers@dotsquares.com>
 * @copyright Copyright (c) 2022 Dotsquares. (http://www.dotsquares.com)
 * @license http://www.dotsquares.com/LICENSE.txt
 */
?>
<?php

$productId = $this->getRequest ()->getParam ( 'id' );
$objectModelManager = \Magento\Framework\App\ObjectManager::getInstance ();
$isLinkEnabled = 0;
$sellerId = $objectModelManager->get ( 'Magento\Catalog\Model\Product' )->load ( $productId )->getSellerId ();
if (! empty ( $sellerId )) {
 $isLinkEnabled = $objectModelManager->get ( 'Dotsquares\Marketplace\Model\Seller' )->load ( $sellerId, 'customer_id' )->getShowProfile ();
}
if ($isLinkEnabled == 1) {
 $seller = $objectModelManager->get ( 'Dotsquares\Marketplace\Helper\Data' );
 $requestPath = $seller->getSellerRequestpath ( $productId );
 $sellerProfile = $seller->getSellerProfile ();
 if ($sellerProfile && $requestPath ['request_path'] != '') {
  ?>
<div class="linker_seller">
    <strong><?php echo __('SELLER'); ?></strong> <a
        href="<?php echo $block->getUrl($requestPath['request_path']);?>"
        class="link_seller">
            <?php echo ucfirst($requestPath['store_name']); ?></a>
</div>
<?php }
}?>