<?php
/**
 * Dotsquares
 * NOTICE OF LICENSE
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.dotsquares.com/LICENSE.txt
 * ==============================================================
 * MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Dotsquares does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Dotsquares does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category Dotsquares
 * @package Dotsquares_Marketplace
 * @version 3.5.2
 * @author Dotsquares Team <developers@dotsquares.com>
 * @copyright Copyright (c) 2022 Dotsquares. (http://www.dotsquares.com)
 * @license http://www.dotsquares.com/LICENSE.txt
 */
?>
<?php
/**
 * New Customer block template
 *
 * @var $block \Magento\Customer\Block\Form\Login\Info
 */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
<div class="block block-new-customer">
    <div class="block-title">
        <strong id="block-new-customer-heading" role="heading"
            aria-level="2"><?php /* @escapeNotVerified */ echo __('New Seller') ?></strong>
    </div>
    <div class="block-content"
        aria-labelledby="block-new-customer-heading">
        <p><?php /* @escapeNotVerified */ echo __('Create a seller account to grow on your business.') ?></p>
        <div class="actions-toolbar">
            <div class="primary">
                <a
                    href="<?php /* @escapeNotVerified */ echo  $block->getUrl('marketplace/seller/create') ?>"
                    class="action create primary"><span><?php /* @escapeNotVerified */ echo __('Create an Account') ?></span></a>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>