<?php 
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$product_id = $block->getcurrentproduct();
	$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
	$enable = $objectManager->get('Dotsquares\Productfaq\Helper\Data')->getConfig('productfaq/general/recaptcha_enabled');
	$site_key = $objectManager->get('Dotsquares\Productfaq\Helper\Data')->getConfig('productfaq/general/recaptcha_site_key');
	$current_url =  $product->getProductUrl();
	$questions = $block->getQuestionCollection();
	#echo'<pre>';print_r($questions->getData());die("tets");
	if($this->getRequest()->getParam('limit')){
		$limit = $this->getRequest()->getParam('limit');	
	}else{
		$limit = 1;
	}
	 
	if($questions->getData()):
	?>
		<div class="product_question_listing">
			<div class="question_toolbar">
				<!--<select id="pagination_tool" class="pagination">
					<option value="0"><?php echo 'Please select'; ?></option>
					<option value="5" <?php if($limit == 5) echo 'selected="selected"' ?>>5</option>
					<option value="10" <?php if($limit == 10) echo 'selected="selected"' ?>>10</option>
					<option value="all" <?php if($limit === 'All') echo 'selected="selected"' ?>>All</option>
				</select>-->
				<?php if ($block->getPagerHtml()): ?>
					<div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
				<?php endif ?>
			</div>
			<div class="product_question_list">
				<ul class="answer_list">
					<?php foreach($questions as $question){?>
						<li>
							<div class="entry-comment">
								<strong>Q: </strong>
								<?php echo $question->getQuestion(); ?>
							</div>
							<p>
								<small class="added-on"><?php echo $question->getCreatedDate(); ?></small>
								<small class="added-on">By: <?php echo $question->getCustomerName(); ?></small>
							</p>
							<div class="entry-answer">
								<strong>A: </strong>
								<?php echo $question->getAnswer(); ?>
							</div>
						</li>	
					<?php }?>
				</ul>
			</div>
		</div>	
	<?php endif; ?>	
	<p class="ask_question"><?php echo 'Ask Question';?></p>
	<p class="close_question" style="display:none"><?php echo 'Close';?></p>
	<div class="Product_alert_content" style="display:none">
		
		<form class="customer_productfaq" data-mage-init='{"validation": {}}' id ="customer_productfaq" autocomplete="off">
			<div class="product_alert">
				<div class="field note no-label">
					<input type="hidden" class="product_id" value="<?php echo $product_id; ?>">
					<?php echo 'Customer Question';?>
					<div class="error_mail_massage" style="background-color: green; padding: 5px 10px; color: #ffffff; width:320px; font-size: 14px; display:none;"></div>
				</div>
				<div class="innnerfaq">
					<div class="field email required">
						<label class="label" for="email"><span>Customer Email</span></label>
						<div class="control">
							<input name="email" id="email" title="Email" value="" class="mail_box input-text" data-validate="{required:true, 'validate-email':true}" aria-required="true" type="email">
						</div>
					</div>
					<div class="field name required">
						<label class="label" for="name"><span>Customer Name</span></label>
						<div class="control">
							<input name="customer_name" id="customer_name" title="customer_name" value="" class="name input-text" type="text" data-validate="{required:true}" aria-required="true">
						</div>
					</div>
					<div class="field question required">
						<label class="label" for="comment"><span>Customer Question</span></label>
						<div class="control">
							<textarea name="question" id="question" title="request qty" class="input-text" cols="5" rows="3" data-validate="{required:true}" aria-required="true"></textarea>
						</div>
					</div>
				</div>
			</div>
			<div class="submit button">
				<button id="mail_content" class="action primary">
					<?php echo "Submit"; ?>
				</button>
			</div>
		</form>	
	</div>
<script>
	require([
		'jquery',
		'mage/mage'
		], function(jQuery){
		
		var dataForm = jQuery('#customer_productfaq');
		var ignore = null;
		dataForm.mage('validation', {
			ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
		}).find('input:text').attr('autocomplete', 'off');
			
		jQuery(document).ready(function(){
			jQuery('#mail_content').click(function () {
				var customer_email = jQuery(".mail_box").val();
				var customer_name = jQuery("#customer_name").val();
				var customer_question = jQuery("#question").val();
				var product_name = jQuery( ".page-title span" ).text();
				var product_id = jQuery( ".product_id" ).val();
				jQuery('.error_mail_massage').hide(); 
				var check = dataForm.validation('isValid');
				if(check ==+true){
					jQuery.ajax
					({
						url: "<?php echo $this->getUrl('productfaq/index')?>",
						type: 'POST', 
						data : {product_id : product_id, product_name : product_name,customer_email : customer_email,customer_question:customer_question,customer_name:customer_name},
						showLoader: true,
						success: function(response) 
						{
							var json = jQuery.parseJSON(response);
							//alert(json.data);
							jQuery('.error_mail_massage').show();
							showLoader: false;
							if(json.data == 'success'){
								jQuery('.error_mail_massage').addClass('success');
								jQuery('.error_mail_massage.success').html('Your Query is successfully submited.');
								setTimeout(function() { jQuery(".error_mail_massage").hide('blind', {}, 500)  }, 5000);
							}else if(json.data == 'error'){
								jQuery('.error_mail_massage').removeClass('success');
								jQuery('.error_mail_massage').html('Incorrect captcha.');
								setTimeout(function() { jQuery(".error_mail_massage").hide('blind', {}, 500)  }, 5000);
							}else{
								jQuery('.error_mail_massage').removeClass('success');
								jQuery('.error_mail_massage').html('You already send.');
								setTimeout(function() { jQuery(".error_mail_massage").hide('blind', {}, 500)  }, 5000);
							}
						}
					});
				}
				return false;
			});
			
			jQuery('.ask_question').click(function (){
				jQuery('.product_question_listing').fadeOut(1000);
				jQuery('.ask_question').fadeOut(1000);
				jQuery('.Product_alert_content').fadeIn(2000);
				jQuery('.close_question').fadeIn(2000);
			});
			
		
			jQuery('.close_question').click(function () {
				jQuery('.Product_alert_content').fadeOut(1000);
				jQuery('.close_question').fadeOut(1000);
				jQuery('.product_question_listing').fadeIn(2000);
				jQuery('.ask_question').fadeIn(2000);
			});
		});	
	});	
</script>