<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php $_product = $block->getProduct() ?>
<?php if ($block->canEmailToFriend()) :?>
   <a href="<?= $block->escapeUrl($this->helper(Magento\Catalog\Helper\Product::class)->getEmailToFriendUrl($_product)) ?>"
       class="action mailto friend"><span><?= $block->escapeHtml(__('Affiliate Email')) ?></span></a>
   <?php if($_product->getAttributeSetId() != 11){ ?>
   <a href="<?= $block->getUrl('contact',['request'=>$_product->getId()]) ?>"
                                       title="Book a live demo"
                                       class="action mailto friend livedemo"><?= $block->escapeHtml(__('Book a live demo')) ?></a>
   <?php }else{ ?>
      <a href="<?= $block->getUrl('contact',['request'=>$_product->getId()]) ?>"
                                       title="Book a live demo"
                                       class="action requestquote mailto friend livedemo"><?= $block->escapeHtml(__('Request a Quote')) ?></a>
   <?php } ?>

<?php endif; ?>
<?php if($_product->getMagentoCompatibility()): ?>
  <div class="compatibility">
      <label class="label"><?= __("Compatible With") ?></label>
      <div class="control">
          <?= $_product->getResource()->getAttribute('magento_compatibility')->getFrontend()->getValue($_product); ?>
      </div>
  </div>
<?php endif; ?>
