<?php
$product = $block->getProduct();
$attributeValue = $product->getResource()->getAttribute('app_location')->getFrontend()->getValue($product);
$andoridlink = $product->getResource()->getAttribute('downloadlink')->getFrontend()->getValue($product);
$ioslink = $product->getResource()->getAttribute('downloadlink2')->getFrontend()->getValue($product);
$imageHelper  = $this->helper('Magento\Catalog\Helper\Image');
$image_url = $imageHelper->init($product, 'product_thumbnail_image')->setImageFile($product->getFile())->resize(450, 450)->getUrl();
?>
<section class="app-banner">
	<div class="app-container">	
		<div class="app-banner-row">
			<div class="app-slider"><img src="<?php echo $image_url;?>"/></div>
			<div class="app-info">
				<h1 class="app-info-title"><?php echo $product->getName(); ?></h1>
				<div class="app-info-desc"><?php echo $product->getShortDescription(); ?></div>
				<div class="app-download-actions">
				    <?php if($ioslink != ""){ ?>
					<a href="<?php echo $ioslink; ?>" target="_blank" class="app-download-btn">
						<div class="icon"><span class="fa-brands fa-apple"></span></div>
						<div class="text">
							Download <span>IOS App</span>
						</div>
					</a>
					<?php } 
					if($andoridlink != ""){ ?>
					
					<a href="<?php echo $andoridlink; ?>" target="_blank" class="app-download-btn">
						<div class="icon"><span class="fa-brands fa-android"></span></div>
						<div class="text">
							Download <span>Andorid App</span>
						</div>
					</a>
					<?php } ?>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="app-feature">
	<h2 class="app-heading">App Feature</h2>
	<div class="app-container">
	<?php echo $product->getDescription(); ?>
		
		<div class="app-help">For any issue please contact us:  <a href="mailto:support.extensions@dotsquares.com">support.extensions@dotsquares.com</a></div>
	</div>
</section>	
	
<section class="app-screens">
	<div class="app-container">
		<h2 class="app-heading">App Screens</h2>
		
		<div class="app-screens-slider stacked-cards">
		<ul class="slider">
		    <?php
		    $images = $product->getMediaGalleryImages();
		    foreach($images as $child){ 
		    ?>
			<li class="item"><img src="<?php echo $child->getUrl(); ?>" alt=""></li>
            <?php } ?> 			
		  </ul>
	</div>
		<div class="app-download-actions">
		    <?php if($ioslink != ""){ ?>
				<a href="<?php echo $ioslink; ?>" target="_blank" class="app-download-btn">
					<div class="icon"><span class="fa-brands fa-apple"></span></div>
					<div class="text">
						Download <span>IOS App</span>
					</div>
				</a>
				<?php } 
					if($andoridlink != ""){ ?>
				
				<a href="<?php echo $andoridlink; ?>" target="_blank" class="app-download-btn">
					<div class="icon"><span class="fa-brands fa-android"></span></div>
					<div class="text">
						Download <span>Andorid App</span>
					</div>
				</a>
				<?php }  ?>
		</div>
	</div>
</section>
	
<section class="app-author">
	<div class="app-container">
		<h2 class="app-heading">App Author Company</h2>
		<div class="app-author-row">
			<div class="app-author-col">
				<div class="app-author-logo">
					<img src="https://stores.dotsquares.com/pub/media/porto/web/images/ds-logo.png" alt="Dotsquares">
				</div>
				<p>Dotsquares is a <strong>CMI Level 3</strong> Company. </p>
<p>Dotsquares head office is based in Albourne (near Brighton and Hove), United Kingdom with international offices in USA, Australia and has in-house development centres in Jaipur, India. 
We work very closely with all our clients, always looking to forge long term relationships, and offer offshore outsourcing services which reduce costs, enhance organisational flexibility and improve business and IT performance. </p>
			</div>
			<div class="app-author-col app-download-message">
				<div class="app-download-heading">
					<h3>Get Your Free Download Of</h3> 
					<h4><?php echo $product->getName(); ?></h4>
					<h5>TODAY !</h5>
				</div>
				
				<div class="app-download-actions">
				<?php if($ioslink != ""){ ?>
				<a href="<?php echo $ioslink; ?>" target="_blank" class="app-download-btn">
					<div class="icon"><span class="fa-brands fa-apple"></span></div>
					<div class="text">
						Download <span>IOS App</span>
					</div>
				</a>
			    <?php } 
					if($andoridlink != ""){ ?>
				
				<a href="<?php echo $andoridlink; ?>" target="_blank" class="app-download-btn">
					<div class="icon"><span class="fa-brands fa-android"></span></div>
					<div class="text">
						Download <span>Andorid App</span>
					</div>
				</a>
				<?php } ?>
			</div>
				
			</div>
		</div>
	</div>
</section>	