<?php
/**

 *
 * @category    Dotsquares
 * @package     Dotsquares_Marketplace
 * @version     3.5.2

 *
 */
?><?php
$helper = $this->helper( 'Dotsquares\Marketplace\Helper\Data' );
$moduleEnabledOrNot = $helper->getModuleEnable ();
if ($moduleEnabledOrNot) {
    ?>
<li class="seller-link">  
<?php
    
$websiteTitle = $this->helper ( 'Dotsquares\Marketplace\Helper\Data' )->getHeadTitle ();
    if (empty ( $websiteTitle )) {
        $websiteTitle = __ ( "Marketplace" );
    }
    ?>
<a <?php echo $block->getLinkAttributes() ?>><?php echo $block->escapeHtml($block->getLabel()).__($websiteTitle)?>  
     <?php echo($block->getCounter()) ? '<span class="counter qty">' . $block->escapeHtml($block->getCounter()) . '</span>' : ''; ?>  
   </a>
</li>
<?php }?>