<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$friendlist =$objectManager->create('Dotsquares\Instagramslider\Helper\Data')->getConfig('instagramslider/general/enable');
$accesstoken =$objectManager->create('Dotsquares\Instagramslider\Helper\Data')->getConfig('instagramslider/general/accesstoken');

$userid =$objectManager->create('Dotsquares\Instagramslider\Helper\Data')->getConfig('instagramslider/general/userid');
$slideritem =$objectManager->create('Dotsquares\Instagramslider\Helper\Data')->getConfig('instagramslider/general/noofitems');
$titles =$objectManager->create('Dotsquares\Instagramslider\Helper\Data')->getConfig('instagramslider/general/instatitle');
$conf = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('instagramslider/general/enable');

if($accesstoken){
    if ($conf) {
 
?>


<div id="instagram-feed">

	<div class="container">
		<h3 class="sc_title sc_title_center sc_lines inner-hed">
			<span><?php  echo $titles; ?></span>
		</h3>			

		<div class="instagraminage">
			<ul class="bxslider">

<?php  
    $timestamp = mktime(date('H'), date('i'), 0, date('n'), date('j') - 1, date('Y'));
     $AccessToken = $accesstoken;
    $instagram_user_id = $userid;
    $url = 'https://graph.instagram.com/'.$instagram_user_id.'/media?access_token=' . $AccessToken;
    $counter = 0;
 	  $feed = $slideritem;

    $ch = curl_init();
 
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_HEADER, false);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
    curl_setopt($ch, CURLOPT_MAXREDIRS, 10);
    curl_setopt($ch, CURLOPT_USERAGENT, 'Instagram Gallery');
 
    $result = curl_exec($ch);
    $http_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
 

    $result = json_decode($result);
    // print_r($result);die();
    if ($result) {

   foreach ($result->data as $media_id){
        $id = $media_id->id;
         
        $counter++;
            //var_dump($slideritem); 
        //die("smp132");

        if( $counter <= $feed ){
               

            if( $id ) { 

                 $url = 'https://graph.instagram.com/'.$id.'?fields=id,media_type,media_url,username,timestamp,permalink&access_token=' . $AccessToken;

                $ch = curl_init();
                curl_setopt($ch, CURLOPT_URL, $url);
                curl_setopt($ch, CURLOPT_HEADER, false);
                curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
                curl_setopt($ch, CURLOPT_MAXREDIRS, 10);
                curl_setopt($ch, CURLOPT_USERAGENT, 'Instagram Gallery');
 
                $result_image = curl_exec($ch);

                $http_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
                curl_close($ch);
                $result_image_link = json_decode($result_image);

 
          ?>

                  <li class="item">
                    <a href="<?php echo $result_image_link->permalink; ?>" target="_blank"> <img src="<?php echo $result_image_link->media_url; ?>" alt="<?php echo '333'; ?>" class="img-responsive" /> </a>
                  </li>
    

        <?php
                    }
                }
            }
    }
  
    
         

        ?>

			</ul>
		</div>
	</div>

</div>

 
 
<script type="text/javascript">
	jQuery('.bxslider').bxSlider({
  auto: true,	
  autoHover: true,
  minSlides: 2,
  maxSlides: 5,
  slideWidth: 240,
   moveSlides: 1,
  slideMargin: 7
});
</script>

<?php } }?>