#commenting this file 
# name: Deploy to FTP Server

# on:
#   push:
#     branches:
#       - staging

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: executing remote ssh commands using password
#         uses: appleboy/ssh-action@v0.1.7
#         with:
#           host: 111.93.56.217
#           username: magento2divya
#           password: Xkdx3tgkC977eHG
#           port: 22
#           script: ls && cd /home/magento2divya/public_html && pwd && php bin/magento setup:upgrade && php bin/magento setup:di:compile && php bin/magento setup:static-content:deploy -f 
