name: Deploy to FTP Server

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        composer install
    - name: Build code
      run: |
        php bin/magento setup:di:compile
        php bin/magento setup:static-content:deploy
    - name: Archive build
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: /home/magento2divya
 
