name: Deploy to FTP Server

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        composer install
    - name: Update dependencies
      run: composer update
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: 192.168.4.28
        username: magento2divya
        password: Xkdx3tgkC977eHG
        server-dir: /home/magento2divya/public_html/
        exclude: var,generated,vendor,pub,setup,stats,phpserver,lib,dev,bin
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: build
    - name: Deploy to FTP Server
      run: |
        apt-get update
        apt-get install lftp -y
        lftp -u magento2divya,Xkdx3tgkC977eHG -e "mirror -R /home/magento2divya ftp://192.168.4.28/; quit"
